In [5]:
import numpy as np
import pandas as pd

In [6]:
df=pd.read_csv(r"E:\500 new with cleaning\500_model_results\TCN_model\classification_report.csv")
df.head()

   Unnamed: 0  precision  recall  f1-score  support
0    1 DOLLAR       0.80     1.0  0.888889      4.0
1   5 DOLLARS       1.00     1.0  1.000000      5.0
2      8 HOUR       0.75     0.6  0.666667      5.0
3    9 OCLOCK       0.80     1.0  0.888889      4.0
4  A LINE BOB       1.00     1.0  1.000000      4.0

In [7]:
df = df.rename(columns={'Unnamed: 0': 'Gloss'})
df.head()

        Gloss  precision  recall  f1-score  support
0    1 DOLLAR       0.80     1.0  0.888889      4.0
1   5 DOLLARS       1.00     1.0  1.000000      5.0
2      8 HOUR       0.75     0.6  0.666667      5.0
3    9 OCLOCK       0.80     1.0  0.888889      4.0
4  A LINE BOB       1.00     1.0  1.000000      4.0

In [9]:
df = df.sort_values(by='f1-score', ascending=False)
df = df.reset_index(drop=True)
df.tail(50)

             Gloss  precision    recall  f1-score  support
453          HAPPY   0.750000  0.600000  0.666667      5.0
454          BRING   0.500000  0.800000  0.615385      5.0
455         SCHOOL   0.600000  0.600000  0.600000      5.0
456        ALRIGHT   0.500000  0.750000  0.600000      4.0
457        KITCHEN   0.600000  0.600000  0.600000      5.0
458           COME   0.600000  0.600000  0.600000      5.0
459         BEFORE   0.600000  0.600000  0.600000      5.0
460           NICE   0.600000  0.600000  0.600000      5.0
461           HEAR   0.600000  0.600000  0.600000     10.0
462         BETTER   0.600000  0.600000  0.600000      5.0
463          STINK   0.600000  0.600000  0.600000      5.0
464           NAME   0.600000  0.600000  0.600000      5.0
465         CANCEL   0.714286  0.500000  0.588235     10.0
466         SINGLE   1.000000  0.400000  0.571429      5.0
467      DIFFERENT   1.000000  0.400000  0.571429      5.0
468          LOAD1   1.000000  0.400000  0.571429      5.0
469            SEE   1.000000  0.400000  0.571429      5.0
470           STOP   0.666667  0.500000  0.571429      4.0
471           MIND   0.500000  0.600000  0.545455      5.0
472           HOUR   0.500000  0.600000  0.545455      5.0
473            ASK   0.500000  0.600000  0.545455      5.0
474            OLD   0.500000  0.600000  0.545455      5.0
475  DOESNT MATTER   0.400000  0.800000  0.533333      5.0
476       BATHROOM   0.428571  0.600000  0.500000      5.0
477            NOW   0.666667  0.400000  0.500000      5.0
478           WHEN   0.666667  0.400000  0.500000      5.0
479           RUDE   0.666667  0.400000  0.500000      5.0
480           GOOD   0.666667  0.400000  0.500000      5.0
481    GRANDMOTHER   0.666667  0.400000  0.500000      5.0
482          THESE   0.375000  0.600000  0.461538      5.0
483           BUSY   0.375000  0.600000  0.461538      5.0
484      THANK YOU   0.500000  0.400000  0.444444      5.0
485           BEST   0.500000  0.400000  0.444444      5.0
486       ASSEMBLY   0.500000  0.400000  0.444444      5.0
487        ATLANTA   0.400000  0.400000  0.400000      5.0
488           WISH   0.400000  0.400000  0.400000      5.0
489         HEALTH   0.333333  0.400000  0.363636      5.0
490          ABOUT   0.500000  0.285714  0.363636      7.0
491       DAUGHTER   1.000000  0.200000  0.333333      5.0
492            AGE   0.500000  0.250000  0.333333      4.0
493       WHATEVER   0.500000  0.200000  0.285714      5.0
494      ASSISTANT   0.222222  0.400000  0.285714      5.0
495          BRAVE   0.333333  0.200000  0.250000      5.0
496         HUNGRY   0.250000  0.250000  0.250000      4.0
497         TOILET   0.333333  0.200000  0.250000      5.0
498          PRICE   0.250000  0.200000  0.222222      5.0
499        SERIOUS   0.200000  0.200000  0.200000      5.0
500      AFTERNOON   0.000000  0.000000  0.000000      4.0
501         ASSIST   0.000000  0.000000  0.000000      5.0
502           SOUR   0.000000  0.000000  0.000000      5.0

In [16]:
(df['f1-score'] < 0.7).sum()

np.int64(68)

In [14]:
df[df['f1-score'] < 0.7]

         Gloss  precision  recall  f1-score  support
435      APPLE   0.571429     0.8  0.666667      5.0
436     TISSUE   0.571429     0.8  0.666667      5.0
437     ANYONE   1.000000     0.5  0.666667      4.0
438      TODAY   0.571429     0.8  0.666667      5.0
439       BATH   0.750000     0.6  0.666667      5.0
..         ...        ...     ...       ...      ...
498      PRICE   0.250000     0.2  0.222222      5.0
499    SERIOUS   0.200000     0.2  0.200000      5.0
500  AFTERNOON   0.000000     0.0  0.000000      4.0
501     ASSIST   0.000000     0.0  0.000000      5.0
502       SOUR   0.000000     0.0  0.000000      5.0

[68 rows x 5 columns]

In [23]:
df[df['Gloss']=='AGE']

    Gloss  precision  recall  f1-score  support
492   AGE        0.5    0.25  0.333333      4.0

In [13]:
df[df['f1-score'] < 0.7]['Gloss'].tolist()

['APPLE',
 'TISSUE',
 'ANYONE',
 'TODAY',
 'BATH',
 'TROUBLE',
 'COLOR',
 'ALL OVER',
 'YEAR',
 '8 HOUR',
 'NIGHT',
 'WIN',
 'PAPER',
 'COST',
 'MEET',
 'MEDICINE',
 'WOMAN',
 'CAREFUL',
 'HAPPY',
 'BRING',
 'SCHOOL',
 'ALRIGHT',
 'KITCHEN',
 'COME',
 'BEFORE',
 'NICE',
 'HEAR',
 'BETTER',
 'STINK',
 'NAME',
 'CANCEL',
 'SINGLE',
 'DIFFERENT',
 'LOAD1',
 'SEE',
 'STOP',
 'MIND',
 'HOUR',
 'ASK',
 'OLD',
 'DOESNT MATTER',
 'BATHROOM',
 'NOW',
 'WHEN',
 'RUDE',
 'GOOD',
 'GRANDMOTHER',
 'THESE',
 'BUSY',
 'THANK YOU',
 'BEST',
 'ASSEMBLY',
 'ATLANTA',
 'WISH',
 'HEALTH',
 'ABOUT',
 'DAUGHTER',
 'AGE',
 'WHATEVER',
 'ASSISTANT',
 'BRAVE',
 'HUNGRY',
 'TOILET',
 'PRICE',
 'SERIOUS',
 'AFTERNOON',
 'ASSIST',
 'SOUR']

In [17]:
class_map = np.load(
    r"E:\500 new with cleaning\500_final_dataset_modified\class_map.npy",
    allow_pickle=True
)

print(class_map)

{'1 DOLLAR': 0, '5 DOLLARS': 1, '8 HOUR': 2, '9 OCLOCK': 3, 'A LINE BOB': 4, 'A LITTLE BIT': 5, 'ABBREVIATE': 6, 'ABOUT': 7, 'ABOVE': 8, 'ABSOLUTELY NOTHING': 9, 'ACCENT': 10, 'ACCEPT': 11, 'ACCESS': 12, 'ACCIDENT': 13, 'ACCOMPLISH': 14, 'ACCORDION': 15, 'ACCOUNTANT': 16, 'ACQUIRE': 17, 'ACT': 18, 'ACTION': 19, 'ACTOR': 20, 'ADD': 21, 'ADDICT': 22, 'ADDRESS': 23, 'ADMIRE': 24, 'ADMIT': 25, 'ADOPT': 26, 'ADULT': 27, 'ADVANTAGE': 28, 'ADVERTISE': 29, 'AFRICA': 30, 'AFTER': 31, 'AFTERNOON': 32, 'AGAIN': 33, 'AGAINST': 34, 'AGE': 35, 'AGENCY': 36, 'AGREEMENT': 37, 'AIRPLANE': 38, 'ALARM': 39, 'ALASKA': 40, 'ALCOHOL': 41, 'ALIGN': 42, 'ALL': 43, 'ALL DAY': 44, 'ALL GONE': 45, 'ALL OF SUDDEN': 46, 'ALL OVER': 47, 'ALL OVER BODY': 48, 'ALL TOGETHER': 49, 'ALL WAY': 50, 'ALONE': 51, 'ALPHABET': 52, 'ALRIGHT': 53, 'ALWAYS': 54, 'AMAZING': 55, 'AMERICA': 56, 'ANALYZE': 57, 'AND': 58, 'ANGEL': 59, 'ANGRY': 60, 'ANIMAL': 61, 'ANNOUNCE': 62, 'ANSWER': 63, 'ANTLERS': 64, 'ANY': 65, 'ANYONE': 66, 'APART': 67, 'APPEAR': 68, 'APPLE': 69, 'APPOINTMENT': 70, 'APRIL': 71, 'ARCHEOLOGY': 72, 'AREA': 73, 'ARGUE': 74, 'ARIZONA': 75, 'ARM': 76, 'ARMY': 77, 'ARREST1': 78, 'ARREST2': 79, 'ARREST3': 80, 'ARRIVE': 81, 'ART': 82, 'ARTICLE': 83, 'ARTICULATE SIGN': 84, 'ASIA': 85, 'ASK': 86, 'ASSEMBLY': 87, 'ASSIGN': 88, 'ASSIST': 89, 'ASSISTANT': 90, 'ASTRONAUT': 91, 'AT': 92, 'ATHLETE': 93, 'ATLANTA': 94, 'ATTENTION': 95, 'ATTITUDE': 96, 'AUDIENCE': 97, 'AUDITORIUM': 98, 'AUNT': 99, 'AUSTRALIA': 100, 'AUTISM1': 101, 'AUTISM2': 102, 'AUTOMATIC': 103, 'AWKWARD': 104, 'BABY': 105, 'BAD': 106, 'BALL': 107, 'BATH': 108, 'BATHROOM': 109, 'BECAUSE': 110, 'BEDROOM': 111, 'BEFORE': 112, 'BEHIND': 113, 'BEST': 114, 'BETTER': 115, 'BICYCLE': 116, 'BIG': 117, 'BIRTH': 118, 'BLUE': 119, 'BODY': 120, 'BOOK': 121, 'BORED': 122, 'BORROW': 123, 'BOSS': 124, 'BOY': 125, 'BRAVE': 126, 'BREAD': 127, 'BREAK': 128, 'BREAKDOWN': 129, 'BRING': 130, 'BROTHER': 131, 'BUS': 132, 'BUSY': 133, 'BUT': 134, 'BUTTER': 135, 'BUY': 136, 'CALL': 137, 'CAMERA': 138, 'CAN': 139, 'CANADA': 140, 'CANCEL': 141, 'CANDY': 142, 'CANNOT': 143, 'CAR': 144, 'CAREFUL': 145, 'CARRY': 146, 'CENTER': 147, 'CHAIR': 148, 'CHALLENGE': 149, 'CHAT': 150, 'CHEAP': 151, 'CHECK': 152, 'CHILD': 153, 'CHILDREN': 154, 'CHOCOLATE': 155, 'CHURCH': 156, 'CITY': 157, 'CLASS': 158, 'CLEAN': 159, 'COFFEE': 160, 'COLD': 161, 'COLLEGE': 162, 'COLOR': 163, 'COME': 164, 'COMFORTABLE': 165, 'COMMUNICATION': 166, 'COMPUTER': 167, 'CONFUSED': 168, 'COOK': 169, 'COOL': 170, 'COST': 171, 'COUNTRY': 172, 'COUSIN': 173, 'CRAZY': 174, 'DAUGHTER': 175, 'DAY': 176, 'DECIDE': 177, 'DIE': 178, 'DIFFERENT': 179, 'DIRTY': 180, 'DIVORCE': 181, 'DOCTOR': 182, 'DOESNT MATTER': 183, 'DONT CARE': 184, 'DONT KNOW': 185, 'DONT LIKE': 186, 'DONT NEED': 187, 'DONT WANT': 188, 'DOOR': 189, 'DOWN': 190, 'DREAM': 191, 'DRINK': 192, 'DRIVE': 193, 'DROP': 194, 'DRUNK': 195, 'EASY': 196, 'EAT': 197, 'EMAIL': 198, 'EMOTION': 199, 'EMPTY': 200, 'ENJOY': 201, 'EQUAL': 202, 'EXCITED': 203, 'EXERCISE': 204, 'EXPENSIVE': 205, 'EXPERIENCE': 206, 'FALL': 207, 'FAMILY': 208, 'FAST': 209, 'FATHER': 210, 'FAVORITE': 211, 'FEEL': 212, 'FIGHT': 213, 'FINE': 214, 'FINGERSPELL': 215, 'FINISH': 216, 'FIX': 217, 'FLOOR': 218, 'FOR': 219, 'FOUR': 220, 'FRANCE': 221, 'FREE': 222, 'FRIDAY': 223, 'FRIEND': 224, 'FRIENDLY': 225, 'FULL': 226, 'FUNNY': 227, 'GAME': 228, 'GET': 229, 'GIRL': 230, 'GIVE': 231, 'GLASSES': 232, 'GO': 233, 'GONE': 234, 'GOOD': 235, 'GRADUATE': 236, 'GRANDFATHER': 237, 'GRANDMOTHER': 238, 'GROUP': 239, 'GROW UP': 240, 'HAIR': 241, 'HAMBURGER': 242, 'HAPPY': 243, 'HARD': 244, 'HAVE': 245, 'HE': 246, 'HEADACHE': 247, 'HEALTH': 248, 'HEAR': 249, 'HEARING': 250, 'HEART': 251, 'HEAVY': 252, 'HELLO': 253, 'HELP': 254, 'HIGH': 255, 'HOCKEY': 256, 'HOME': 257, 'HONEST': 258, 'HONOR': 259, 'HOSPITAL': 260, 'HOT': 261, 'HOTDOG': 262, 'HOUR': 263, 'HOUSE': 264, 'HOW': 265, 'HUNGRY': 266, 'I LOVE YOU': 267, 'IF': 268, 'IMAGINE': 269, 'IMPORTANT': 270, 'IMPOSSIBLE': 271, 'IN': 272, 'INTERNET': 273, 'INVITE': 274, 'JACKET': 275, 'JEALOUS': 276, 'KEY': 277, 'KID': 278, 'KITCHEN': 279, 'KNIFE': 280, 'KNOW': 281, 'LANGUAGE': 282, 'LAST': 283, 'LATE': 284, 'LATER': 285, 'LAUGH': 286, 'LEARN': 287, 'LEAVE': 288, 'LECTURE': 289, 'LEFT': 290, 'LEND': 291, 'LETTER': 292, 'LIBRARY': 293, 'LIGHT': 294, 'LIKE': 295, 'LISTEN': 296, 'LIVE': 297, 'LOAD1': 298, 'LONELY': 299, 'LONG': 300, 'LOOK FOR': 301, 'LOUD': 302, 'MACHINE': 303, 'MAGAZINE': 304, 'MAKE': 305, 'MAN': 306, 'MARRY': 307, 'MAYBE': 308, 'ME': 309, 'MEAN': 310, 'MEDICINE': 311, 'MEET': 312, 'MEETING': 313, 'MILK': 314, 'MIND': 315, 'MISS': 316, 'MISUNDERSTAND': 317, 'MODEL': 318, 'MONDAY': 319, 'MONEY1': 320, 'MONEY2': 321, 'MONTH': 322, 'MORE': 323, 'MORNING': 324, 'MOST': 325, 'MOTHER': 326, 'MUCH': 327, 'MUST': 328, 'MY': 329, 'NAME': 330, 'NEW': 331, 'NICE': 332, 'NIGHT': 333, 'NO': 334, 'NONE': 335, 'NOT': 336, 'NOW': 337, 'NUMBERS': 338, 'NURSE': 339, 'OFFICE': 340, 'OH I SEE': 341, 'OLD': 342, 'ONION': 343, 'OTHER': 344, 'OUT': 345, 'PAIN': 346, 'PAPER': 347, 'PARENTS': 348, 'PARK': 349, 'PAST': 350, 'PATIENT': 351, 'PEN': 352, 'PENCIL': 353, 'PEOPLE': 354, 'PERSON': 355, 'PHONE': 356, 'PITY': 357, 'PLAY': 358, 'PLEASE': 359, 'POOR': 360, 'POTATO': 361, 'PRACTICE': 362, 'PRESIDENT': 363, 'PRETTY': 364, 'PRICE': 365, 'PRINT': 366, 'QUIET': 367, 'RAIN': 368, 'READ': 369, 'READY': 370, 'REASON': 371, 'RELATIONSHIP': 372, 'RELAX': 373, 'RESTAURANT': 374, 'RICH': 375, 'RIGHT': 376, 'ROOM': 377, 'RUDE': 378, 'RUN': 379, 'SAD': 380, 'SALAD': 381, 'SAME': 382, 'SCARED': 383, 'SCHOOL': 384, 'SEE': 385, 'SELF': 386, 'SELL': 387, 'SERIOUS': 388, 'SHOP': 389, 'SHOULD': 390, 'SHOW': 391, 'SHOWER': 392, 'SHY': 393, 'SICK': 394, 'SINGLE': 395, 'SISTER': 396, 'SIT': 397, 'SLEEP': 398, 'SLOW': 399, 'SMALL': 400, 'SMART': 401, 'SON': 402, 'SORRY': 403, 'SOUR': 404, 'STAND': 405, 'START': 406, 'STATE': 407, 'STAY': 408, 'STILL': 409, 'STINK': 410, 'STOP': 411, 'STRANGE': 412, 'STRESS': 413, 'STRONG': 414, 'STUBBORN': 415, 'STUDENT': 416, 'STUDY': 417, 'STUPID': 418, 'SUMMER': 419, 'SURE': 420, 'SURPRISE': 421, 'TABLE': 422, 'TAKE': 423, 'TAKE CARE': 424, 'TALL': 425, 'TEA': 426, 'TEACH': 427, 'TEACHER': 428, 'TEAM': 429, 'TELL': 430, 'TEST': 431, 'THANK YOU': 432, 'THAT': 433, 'THESE': 434, 'THEY': 435, 'THIN': 436, 'THIRSTY': 437, 'THREE': 438, 'THURSDAY': 439, 'TIME': 440, 'TIRED': 441, 'TISSUE': 442, 'TODAY': 443, 'TOILET': 444, 'TOMORROW': 445, 'TRAIN': 446, 'TRAVEL': 447, 'TROUBLE': 448, 'TRY': 449, 'TV': 450, 'TWO': 451, 'TYPE': 452, 'UGLY': 453, 'UNCLE': 454, 'UNDERSTAND': 455, 'UNIVERSITY': 456, 'UP': 457, 'VACATION': 458, 'VISIT': 459, 'WAIT': 460, 'WALK': 461, 'WANT': 462, 'WARM': 463, 'WARN': 464, 'WASH': 465, 'WATER': 466, 'WE': 467, 'WEAK': 468, 'WEAR': 469, 'WEDNESDAY': 470, 'WEEK': 471, 'WELCOME': 472, 'WHAT': 473, 'WHAT FOR': 474, 'WHATEVER': 475, 'WHEN': 476, 'WHERE': 477, 'WHICH': 478, 'WHO': 479, 'WHY': 480, 'WIFE': 481, 'WILL': 482, 'WIN': 483, 'WINDOW': 484, 'WISE': 485, 'WISH': 486, 'WOLF': 487, 'WOMAN': 488, 'WONDER': 489, 'WORK': 490, 'WORLD': 491, 'WORRY': 492, 'WRITE': 493, 'YEAR': 494, 'YES': 495, 'YESTERDAY': 496, 'YOU': 497, 'YOUNG': 498, 'YOUR': 499}

In [20]:
low_glosses = set(df[df['f1-score'] < 0.7]['Gloss'])

matching_indices = [
    class_map[gloss]
    for gloss in low_glosses
    if gloss in class_map
]

print(matching_indices)

[448, 483, 365, 53, 333, 32, 109, 94, 66, 133, 266, 312, 342, 488, 332, 2, 163, 179, 330, 298, 248, 263, 69, 434, 112, 35, 347, 145, 141, 126, 442, 411, 175, 378, 108, 249, 235, 130, 337, 486, 171, 315, 432, 183, 443, 384, 444, 89, 311, 475, 279, 388, 243, 238, 494, 410, 47, 115, 86, 87, 476, 7, 404, 385, 114, 90, 164, 395]

In [25]:
from pathlib import Path
import numpy as np

root = Path(r"E:\500 new with cleaning\500_final_dataset_modified")
remove_indices = set(matching_indices)

deleted = 0

for split in ["train", "val", "test"]:
    split_dir = root / split

    for file in split_dir.glob("*.npz"):
        try:
            with np.load(file) as data:   # 👈 IMPORTANT FIX
                y = int(data["y"])

            if y in remove_indices:
                file.unlink()
                deleted += 1

        except Exception as e:
            print(f"Error: {file} -> {e}")

print(f"Deleted {deleted} files")

Deleted 6464 files

In [26]:
from pathlib import Path
import numpy as np

root = Path(r"E:\500 new with cleaning\500_final_dataset_modified")

all_classes = set()

for split in ["train", "val", "test"]:
    split_dir = root / split

    for file in split_dir.glob("*.npz"):
        with np.load(file) as data:
            all_classes.add(int(data["y"]))

print("Number of remaining classes:", len(all_classes))

Number of remaining classes: 432